//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentFeedbackSystem.StudentPages
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Literal litStudentFullName;
        protected global::System.Web.UI.WebControls.Literal litStudentNumber;
        protected global::System.Web.UI.WebControls.Literal litProgram;
        protected global::System.Web.UI.WebControls.Literal litYearLevel;
        protected global::System.Web.UI.WebControls.Literal litSectionName;
        protected global::System.Web.UI.WebControls.Literal litCurrentDate;
        protected global::System.Web.UI.WebControls.Panel pnlPendingNotice;
        protected global::System.Web.UI.WebControls.Literal litPendingAlertCount;
        protected global::System.Web.UI.WebControls.Literal litTotalCoursesCount;
        protected global::System.Web.UI.WebControls.Literal litPendingCount;
        protected global::System.Web.UI.WebControls.Literal litCompletedCount;
        protected global::System.Web.UI.WebControls.GridView gvPendingCourses;
    }
}
