//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentFeedbackSystem.StudentPages
{
    public partial class MyCourses
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.LinkButton btnTabAll;
        protected global::System.Web.UI.WebControls.Literal litCountAll;
        protected global::System.Web.UI.WebControls.LinkButton btnTabPending;
        protected global::System.Web.UI.WebControls.Literal litCountPending;
        protected global::System.Web.UI.WebControls.LinkButton btnTabCompleted;
        protected global::System.Web.UI.WebControls.Literal litCountCompleted;
        protected global::System.Web.UI.WebControls.DropDownList ddlTermFilter;
        protected global::System.Web.UI.WebControls.HiddenField hidFilter;
        protected global::System.Web.UI.WebControls.GridView gvCourses;
    }
}
