//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentFeedbackSystem.StudentPages
{
    public partial class MyRatingHistory
    {
        protected global::System.Web.UI.WebControls.Literal litHistoryCount;
        protected global::System.Web.UI.WebControls.GridView gvHistory;
    }
}
