//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentFeedbackSystem.StudentPages
{
    public partial class RateCourse
    {
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litErrorMessage;
        protected global::System.Web.UI.WebControls.Literal litCourseCode;
        protected global::System.Web.UI.WebControls.Literal litUnits;
        protected global::System.Web.UI.WebControls.Literal litSectionName;
        protected global::System.Web.UI.WebControls.Literal litCourseTitle;
        protected global::System.Web.UI.WebControls.Literal litSchoolYear;
        protected global::System.Web.UI.WebControls.Literal litTerm;
        protected global::System.Web.UI.WebControls.Literal litProfessorName;
        protected global::System.Web.UI.WebControls.Literal litDepartment;
        protected global::System.Web.UI.WebControls.Repeater rptCriteria;
        protected global::System.Web.UI.WebControls.TextBox txtComments;
        protected global::System.Web.UI.WebControls.CheckBox chkAnonymous;
        protected global::System.Web.UI.WebControls.Button btnSubmitRating;
    }
}
