//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentFeedbackSystem.AdminPages
{
    public partial class AuditLog
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterAction;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterTargetType;
        protected global::System.Web.UI.WebControls.TextBox txtSearchTerm;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Literal litLogCount;
        protected global::System.Web.UI.WebControls.GridView gvAuditLog;
    }
}
