//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentFeedbackSystem.AdminPages
{
    public partial class ManageCriteria
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.Panel pnlEditor;
        protected global::System.Web.UI.WebControls.Literal litEditorTitle;
        protected global::System.Web.UI.WebControls.HiddenField hidCriterionId;
        protected global::System.Web.UI.WebControls.TextBox txtCriterionName;
        protected global::System.Web.UI.WebControls.TextBox txtWeight;
        protected global::System.Web.UI.WebControls.TextBox txtDisplayOrder;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Literal litActiveCount;
        protected global::System.Web.UI.WebControls.GridView gvCriteria;
    }
}
