//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentFeedbackSystem.AdminPages
{
    public partial class ManageProfessors
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.Panel pnlEditor;
        protected global::System.Web.UI.WebControls.Literal litEditorTitle;
        protected global::System.Web.UI.WebControls.HiddenField hidProfessorId;
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartment;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.GridView gvProfessors;
        protected global::System.Web.UI.WebControls.Literal litTotalProfessorsCount;
        protected global::System.Web.UI.WebControls.Literal litActiveProfessorsCount;
        protected global::System.Web.UI.WebControls.Literal litDepartmentCount;
    }
}
