//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentFeedbackSystem.AdminPages
{
    public partial class ManageSections
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.Panel pnlSectionEditor;
        protected global::System.Web.UI.WebControls.Literal litSectionEditorTitle;
        protected global::System.Web.UI.WebControls.HiddenField hidSectionId;
        protected global::System.Web.UI.WebControls.TextBox txtSectionName;
        protected global::System.Web.UI.WebControls.DropDownList ddlSectionYearLevel;
        protected global::System.Web.UI.WebControls.DropDownList ddlSectionProgram;
        protected global::System.Web.UI.WebControls.TextBox txtSchoolYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlTerm;
        protected global::System.Web.UI.WebControls.Button btnSaveSection;
        protected global::System.Web.UI.WebControls.Button btnCancelSection;
        protected global::System.Web.UI.WebControls.GridView gvSections;
        protected global::System.Web.UI.WebControls.Panel pnlOfferingEditor;
        protected global::System.Web.UI.WebControls.DropDownList ddlOfferingCourse;
        protected global::System.Web.UI.WebControls.DropDownList ddlOfferingProfessor;
        protected global::System.Web.UI.WebControls.DropDownList ddlOfferingSection;
        protected global::System.Web.UI.WebControls.TextBox txtOfferingSchoolYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlOfferingTerm;
        protected global::System.Web.UI.WebControls.Button btnSaveOffering;
        protected global::System.Web.UI.WebControls.GridView gvOfferings;
        protected global::System.Web.UI.WebControls.Panel pnlAssignment;
        protected global::System.Web.UI.WebControls.TextBox txtAssignStudentNumber;
        protected global::System.Web.UI.WebControls.DropDownList ddlAssignSection;
        protected global::System.Web.UI.WebControls.Button btnAssignStudent;
        protected global::System.Web.UI.WebControls.Panel pnlBulkAssignment;
        protected global::System.Web.UI.WebControls.FileUpload fuSectionCsv;
        protected global::System.Web.UI.WebControls.DropDownList ddlBulkFallbackSection;
        protected global::System.Web.UI.WebControls.TextBox txtBulkCsv;
        protected global::System.Web.UI.WebControls.Button btnProcessBulkCsv;
        protected global::System.Web.UI.WebControls.Panel pnlBulkResults;
        protected global::System.Web.UI.WebControls.Literal litBulkResultSummary;
        protected global::System.Web.UI.WebControls.HiddenField hidActiveTab;
        protected global::System.Web.UI.WebControls.Literal litTotalSectionsCount;
        protected global::System.Web.UI.WebControls.Literal litTotalOfferingsCount;
    }
}
