//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentFeedbackSystem.AdminPages
{
    public partial class ManageCourses
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.Panel pnlEditor;
        protected global::System.Web.UI.WebControls.Literal litEditorTitle;
        protected global::System.Web.UI.WebControls.HiddenField hidCourseId;
        protected global::System.Web.UI.WebControls.TextBox txtCourseCode;
        protected global::System.Web.UI.WebControls.TextBox txtCourseTitle;
        protected global::System.Web.UI.WebControls.TextBox txtUnits;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.GridView gvCourses;
        protected global::System.Web.UI.WebControls.Literal litTotalCoursesCount;
        protected global::System.Web.UI.WebControls.Literal litActiveCoursesCount;
        protected global::System.Web.UI.WebControls.Literal litInactiveCoursesCount;
    }
}
