//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentFeedbackSystem.AdminPages
{
    public partial class RatingResults
    {
        protected global::System.Web.UI.WebControls.Button btnExportCsv;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.Literal litInstAverage;
        protected global::System.Web.UI.WebControls.Literal litTotalSubmissions;
        protected global::System.Web.UI.WebControls.Literal litCountVerySatisfactory;
        protected global::System.Web.UI.WebControls.Literal litCountSatisfactory;
        protected global::System.Web.UI.WebControls.Literal litCountBelowSatisfactory;
        protected global::System.Web.UI.WebControls.TextBox txtFilterSchoolYear;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterTerm;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterDepartment;
        protected global::System.Web.UI.WebControls.TextBox txtSearchQuery;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Button btnResetFilter;
        protected global::System.Web.UI.WebControls.Literal litResultCount;
        protected global::System.Web.UI.WebControls.GridView gvRatingResults;
        protected global::System.Web.UI.WebControls.Panel pnlDrillDown;
        protected global::System.Web.UI.WebControls.Literal litDrillProfessorName;
        protected global::System.Web.UI.WebControls.Button btnCloseDrillDown;
        protected global::System.Web.UI.WebControls.Literal litDrillDepartment;
        protected global::System.Web.UI.WebControls.Literal litDrillCourses;
        protected global::System.Web.UI.WebControls.Literal litDrillAverage;
        protected global::System.Web.UI.WebControls.Literal litDrillClassificationBadge;
        protected global::System.Web.UI.WebControls.GridView gvDrillCriteria;
        protected global::System.Web.UI.WebControls.Literal litDrillCommentsCount;
        protected global::System.Web.UI.WebControls.Repeater rptComments;
        protected global::System.Web.UI.WebControls.Panel pnlNoComments;
        protected global::System.Web.UI.WebControls.HiddenField hidChartClassificationData;
        protected global::System.Web.UI.WebControls.HiddenField hidChartFacultyScores;
    }
}
