//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentFeedbackSystem
{
    public partial class Register
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        protected global::System.Web.UI.WebControls.Literal litMessage;

        protected global::System.Web.UI.WebControls.TextBox txtFirstName;

        protected global::System.Web.UI.WebControls.TextBox txtMiddleName;

        protected global::System.Web.UI.WebControls.TextBox txtLastName;

        protected global::System.Web.UI.WebControls.TextBox txtStudentNumber;

        protected global::System.Web.UI.WebControls.TextBox txtSchoolEmail;

        protected global::System.Web.UI.WebControls.TextBox txtBirthDate;

        protected global::System.Web.UI.WebControls.DropDownList ddlProgram;

        protected global::System.Web.UI.WebControls.DropDownList ddlYearLevel;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;

        protected global::System.Web.UI.WebControls.Button btnRegister;
    }
}
