//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentFeedbackSystem
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm mainForm;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor brandLink;
        protected global::System.Web.UI.WebControls.LoginName LoginName1;

        protected global::System.Web.UI.WebControls.Panel pnlAdminSidebar;
        protected global::System.Web.UI.WebControls.Literal litAdminUsername;
        protected global::System.Web.UI.WebControls.Literal litAdminRoleBadge;
        protected global::System.Web.UI.WebControls.Literal litSidebarPendingBadge;
        protected global::System.Web.UI.WebControls.LinkButton lnkSidebarLogout;
        protected global::System.Web.UI.WebControls.Panel pnlStudentSidebar;
        protected global::System.Web.UI.WebControls.Literal litStudentUsername;
        protected global::System.Web.UI.WebControls.Literal litStudentPendingBadge;
        protected global::System.Web.UI.WebControls.LinkButton lnkStudentSidebarLogout;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder TitleContent;
    }
}
